Controllers/CryptoController.cs
using Microsoft.AspNetCore.Mvc;
using MyProjectWeb.Models;
using Newtonsoft.Json;

namespace MyProjectWeb.Controllers
{
  public class CryptoController : Controller
  {
    private static readonly HttpClient _httpClient;
    static CryptoController()
    {
      _httpClient = new HttpClient();
      _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue(REDACTED);
    }


    [Microsoft.AspNetCore.Mvc.HttpGet]
    public IActionResult News()
    {
      var resp = GetNews().Result;
      CryptoNews newsFeed = JsonConvert.DeserializeObject<CryptoNews>(resp);
      return View(newsFeed);
    }

    [Microsoft.AspNetCore.Mvc.HttpGet]
    public IActionResult Prices()
    {
      var resp = GetPrices().Result;
      CryptoPrices pricesFeed = JsonConvert.DeserializeObject<CryptoPrices>(resp);
      return View(pricesFeed);
    }

    public async Task<string> GetNews()
    {
      var result = await GetExternalResponse("https://doubloon-api.herokuapp.com/crypto/news");
      return new string(result);
    }

    public async Task<string> GetPrices()
    {
      var result = await GetExternalResponse("https://doubloon-api.herokuapp.com/crypto/prices");
      return new string(result);
    }

    private async Task<string> GetExternalResponse(string url)
    {
      HttpResponseMessage response = await _httpClient.GetAsync(url);
      response.EnsureSuccessStatusCode();
      var result = await response.Content.ReadAsStringAsync();
      return result;
    }
  }
}

Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using MyProjectWeb.Models;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MyProjectWeb.Controllers
{
  public class StockController : Controller
  {
    private static readonly HttpClient _httpClient;

    static StockController()
    {
      _httpClient = new HttpClient();
      _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue(REDACTED);
    }

    [Microsoft.AspNetCore.Mvc.HttpGet]
    public IActionResult News()
    {
      var resp = GetNews().Result;
      StockNews newsFeed = JsonConvert.DeserializeObject<StockNews>(resp);
      return View(newsFeed);
    }

    [Microsoft.AspNetCore.Mvc.HttpGet]
    public IActionResult Prices()
    {
      var resp = GetPrices().Result;
      StockPrices pricesFeed = JsonConvert.DeserializeObject<StockPrices>(resp);
      return View(pricesFeed);
    }

    public async Task<string> GetPrices()
    {
      var result = await GetExternalResponse("https://doubloon-api.herokuapp.com/stocks/prices");
      return new string(result);
    }

    public async Task<string> GetNews()
    {
      var result = await GetExternalResponse("https://doubloon-api.herokuapp.com/stocks/news");
      return new string(result);
    }

    private async Task<string> GetExternalResponse(string url)
    {
      HttpResponseMessage response = await _httpClient.GetAsync(url);
      response.EnsureSuccessStatusCode();
      var result = await response.Content.ReadAsStringAsync();
      return result;
    }
  }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - MyProjectWeb</title>
  <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
  <link rel="stylesheet" href="~/css/site.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" />
</head>
<body>
  <header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Doubloon</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" asp-controller="Crypto" asp-action="News">Crypto News</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-controller="Crypto" asp-action="Prices">Crypto Prices</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-controller="Stock" asp-action="News">Stock News</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-controller="Stock" asp-action="Prices">Stock Prices</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-controller="Home" asp-action="Legal">Legal Disclaimer</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

  </header>

  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2022 - Doubloon - <a asp-area="" asp-controller="Home" asp-action="About">About This Project</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>